FILESDIR = ${ETCBASE}/sysinit/base

FILES = 10-pseudofs.sh \
	20-fsck_root.sh \
	30-ksetup.sh

# TODO: will become automatic by the build system later
FILESBUILD.30-ksetup.sh = yes

.include <rf/all.mk>
